var messages = new Array();

function loadLanguage(lang) {
    switch (lang) {
        case "nb-no":
            messages = messages_nb_no;
            break;
        case "de":
            messages = messages_de;
            break;
        case "du-nl":
            messages = messages_du_nl;
            break;
        case "pt-br":
            messages = messages_pt_br;
            break;
        case "se-se":
            messages = messages_se_se;
            break;
	    case "fr-fr":
            messages = messages_fr_fr;
            break;
	    case "cn-cn":
            messages = messages_cn_cn;
            break;
        case "it-it":
            messages = messages_it_it;
            break;
        case "pl-pl":
            messages = messages_pl_pl;
            break;
        default:
            messages = messages_en_us;
            break;
    }
}

var messages_en_us = {
    unknown: "Unknown",
    running: "Running",
    stopped: "Stopped",
    paused: "Paused",
    suspended: "Suspended",
    starting: "Starting",
    snapshot: "Snapshot",
    saving: "Saving",
    stopping: "Stopping",
    pausing: "Pausing",
    resuming: "Resuming",

    NumberOfProcessors: "Processors:",
    ProcessorLoad: "Processor load:",
    MemoryUsage: "Memory usage:",
    HeartBeat: "Heart beat:",
    HeartBeatOK: "OK",
    HeartBeatERR: "Error",
    HeartBeatNCO: "No contact",
    HeartBeatLCO: "Lost communication",
    Uptime: "Up-time:",
    Uptimedays: "d",
    Uptimehours: "h",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "Operating system:",
    HealthState: "Health:",
    HealthStateOK: "OK",
    HealthStateERR: "Failure",
    HealthStateCRI: "Critical failure",
    ConnectionType: "Connection type:",
    
    start: "Start",
    turnOff: "Turn Off",
    shutDown: "Shut Down",
    save: "Save",
    pause: "Pause",
    resume: "Resume",

    offline: "Offline",
    pingTimeout: "Ping timeout",
    
    newServer: "New",
    removeServer: "Delete",
    saveServer: "Save",
    
    serverLabel: "Server",
    requiredLabel: "Required",
    
    usernameLabel: "Username",
    passwordLabel: "Password",
    connectionLabel: "Remote desktop",
    consoleOption: "Console",
    terminalOption: "Terminal",
    bothOption: "Both",
    noneOption: "Neither",
    macAddressLabel: "MAC Address",
    ipAddressLabel: "IP Address",
    udpPortLabel: "UDP Port",
    wakeOnLanLabel: "Wake on Lan",
    
    refreshTime: "Refresh Time",
    seconds: "seconds",
    showVMLabel: "Show",
    VMLabel: "virtual machines",
    VMDetailsLabel: "Details",
    VMCPULabel: "CPU graph",
    clickBehaviour: "Click Behaviour",
    ondblclickOption: "Double Click",
    onclickOption: "Single Click",
    serverControl: "Server Control",
    
    madeBy: "Made by",
    and: "and",
    version: "Version",
    checkUpdates: "Check for updates",
    
    generalTab: "General",
    serverTab: "Servers",

    language: "Language",
    translationdBy: "Translation by",
    translationdByName: "Tore Lervik"
};

var messages_nb_no = {
    unknown: "Ukjent",
    running: "Kjører",
    stopped: "Stoppet",
    paused: "Pauset",
    suspended: "Avslått",
    starting: "Starter",
    snapshot: "Speilbilde",
    saving: "Lagrer",
    stopping: "Stopper",
    pausing: "Pauser",
    resuming: "Restarter",

    NumberOfProcessors: "Prosessorer:",
    ProcessorLoad: "Prosessorlast:",
    MemoryUsage: "Minnebruk:",
    HeartBeat: "Hjerterytme:",
    HeartBeatOK: "OK",
    HeartBeatERR: "Feil",
    HeartBeatNCO: "Ingen kontakt",
    HeartBeatLCO: "Tapt kommunikasjon",
    Uptime: "Oppetid:",
    Uptimedays: "d",
    Uptimehours: "t",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "Operativsystem:",
    HealthState: "Helse:",
    HealthStateOK: "OK",
    HealthStateERR: "Feil",
    HealthStateCRI: "Kritisk feil",
    ConnectionType: "Tilkoblingstype:",

    start: "Slå på",
    turnOff: "Skru av",
    shutDown: "Avslutt",
    save: "Lagre",
    pause: "Pause",
    resume: "Slå på",

    offline: "Avslått",
    pingTimeout: "Ping-timeout",

    newServer: "Ny",
    removeServer: "Slett",
    saveServer: "Lagre",

    serverLabel: "Server",
    requiredLabel: "Påkrevd",

    usernameLabel: "Brukernavn",
    passwordLabel: "Passord",
    connectionLabel: "Remote desktop",
    consoleOption: "Console",
    terminalOption: "Terminal",
    bothOption: "Begge",
    noneOption: "Ingen",
    macAddressLabel: "MAC-Adresse",
    ipAddressLabel: "IP-Adresse",
    udpPortLabel: "UDP-Port",
    wakeOnLanLabel: "Wake on Lan",

    refreshTime: "Oppdateringsfrekvens",
    seconds: "sekunder",
    showVMLabel: "Viser",
    VMLabel: "virtuella maskiner",
    VMDetailsLabel: "Detaljer",
    VMCPULabel: "CPU graf",
    clickBehaviour: "Klikktype",
    ondblclickOption: "Dobbelklikk",
    onclickOption: "Singleklikk",
    serverControl: "Serverkontroll",

    madeBy: "Laget av",
    and: "og",
    version: "Versjon",
    checkUpdates: "Se etter oppdateringer",

    generalTab: "Generelt",
    serverTab: "Servere",

    language: "Språk",
    translationdBy: "Oversatt av",
    translationdByName: "Tore Lervik"
};

var messages_de = {
    unknown: "Unbekannt",
    running: "Gestartet",
    stopped: "Gestoppt",
    paused: "Pausiert",
    suspended: "Ruhend",
    starting: "Startet",
    snapshot: "Snapshot",
    saving: "Speichern",
    stopping: "Stoppen",
    pausing: "Pausieren",
    resuming: "Startet",

    NumberOfProcessors: "Prozessoren",
    ProcessorLoad: "Prozessor-Belastung:",
    MemoryUsage: "Memory usage:",
    HeartBeat: "Heart Beat",
    HeartBeatOK: "OK",
    HeartBeatERR: "Error",
    HeartBeatNCO: "Kein Kontakt",
    HeartBeatLCO: "Lost Kommunikation",
    Uptime: "Up-Time:",
    Uptimedays: "d",
    Uptimehours: "h",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "Betriebssystem:",
    HealthState: "Gesundheit",
    HealthStateOK: "OK",
    HealthStateERR: "Failure",
    HealthStateCRI: "Kritische Fehler",
    ConnectionType: "Connection type:",

    start: "Starten",
    turnOff: "Ausschalten",
    shutDown: "Herunterfahren",
    save: "Speichern",
    pause: "Pausieren",
    resume: "Wiederaufnehmen",

    offline: "Offline",
    pingTimeout: "Ping Timeout",

    newServer: "Neu",
    removeServer: "Löschen",
    saveServer: "Speichern",

    serverLabel: "Server",
    requiredLabel: "benötigt",

    usernameLabel: "Benutzername",
    passwordLabel: "Passwort",
    connectionLabel: "Remote desktop",
    consoleOption: "Console",
    terminalOption: "Terminal",
    bothOption: "Beides",
    noneOption: "Keines",
    macAddressLabel: "MAC Adresse",
    ipAddressLabel: "IP Adresse",
    udpPortLabel: "UDP Port",
    wakeOnLanLabel: "Wake on Lan",

    refreshTime: "Aktualisierung",
    seconds: "Sekunden",
    showVMLabel: "Zeig",
    VMLabel: "Virtuelle Maschinen",
    VMDetailsLabel: "Details",
    VMCPULabel: "CPU Graphen",
    clickBehaviour: "Klicktyp",
    ondblclickOption: "Doppelklick",
    onclickOption: "Einzelklick",
    serverControl: "Serverkontrolle",

    madeBy: "Erstellt von",
    and: "und",
    version: "Version",
    checkUpdates: "Auf Updates prüfen",

    generalTab: "Allgemein",
    serverTab: "Servers",

    language: "Sprache",
    translationdBy: "Übersetzt von",
    translationdByName: "Bjoern Buerstinghaus"
};

var messages_du_nl = {
    unknown: "Onbekend",
    running: "Aan",
    stopped: "Uit",
    paused: "Pauze",
    suspended: "Slapend",
    starting: "Starten",
    snapshot: "Snapshot",
    saving: "Opslaan",
    stopping: "Stoppen",
    pausing: "Pauzeren",
    resuming: "Hervatten",

    NumberOfProcessors: "Processoren:",
    ProcessorLoad: "Processorbelasting:",
    MemoryUsage: "Geheugengebruik:",
    HeartBeat: "Hartslag:",
    HeartBeatOK: "OK",
    HeartBeatERR: "Fout",
    HeartBeatNCO: "Geen contact",
    HeartBeatLCO: "Verbinding verbroken",
    Uptime: "Uptime:",
    Uptimedays: "d",
    Uptimehours: "u",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "Operating systeem:",
    HealthState: "Gezondheid:",
    HealthStateOK: "OK",
    HealthStateERR: "Fout",
    HealthStateCRI: "Kritische fout",
    ConnectionType: "Connectietype:",

    start: "Starten",
    turnOff: "Uitzetten",
    shutDown: "Afsluiten",
    save: "Opslaan",
    pause: "Pauzeren",
    resume: "Hervatten",

    offline: "Offline",
    pingTimeout: "Ping Timeout",

    newServer: "Nieuw",
    removeServer: "Verwijderen",
    saveServer: "Opslaan",

    serverLabel: "Server",
    requiredLabel: "verplicht",

    usernameLabel: "Gebruikersnaam",
    passwordLabel: "Wachtwoord",
    connectionLabel: "Remote desktop",
    consoleOption: "Console",
    terminalOption: "Terminal",
    bothOption: "Beide",
    noneOption: "Geen",
    macAddressLabel: "MAC Adres",
    ipAddressLabel: "IP Adres",
    udpPortLabel: "UDP Poort",
    wakeOnLanLabel: "Wake on Lan",

    refreshTime: "Verversing",
    seconds: "seconden",
    showVMLabel: "Toon",
    VMLabel: "virtuele machines",
    VMDetailsLabel: "Details",
    VMCPULabel: "CPU Grafiek",
    clickBehaviour: "Klik type",
    ondblclickOption: "Dubbelklikken",
    onclickOption: "Klikken",
    serverControl: "Server beheer",

    madeBy: "Ontwikkeld door",
    and: "en",
    version: "Versie",
    checkUpdates: "Op updates controleren",

    generalTab: "Algemeen",
    serverTab: "Servers",

    language: "Taal",
    translationdBy: "Vertaald door",
    translationdByName: "Wibout Bootsma"
};

var messages_pt_br = {
    unknown: "Desconhecido",
    running: "Executando",
    stopped: "Parado",
    paused: "Pausado",
    suspended: "Suspenso",
    starting: "Iniciando",
    snapshot: "Snapshot",
    saving: "Salvando",
    stopping: "Parando",
    pausing: "Pausando",
    resuming: "Iniciando",

    NumberOfProcessors: "O transformador",
    ProcessorLoad: "a carga do processador:",
    MemoryUsage: "Memória",
    HeartBeat: "Heart Beat",
    HeartBeatOK: "OK",
    HeartBeatERR: "Erro",
    HeartBeatNCO: "No contato",
    HeartBeatLCO: "Lost comunicação",
    Uptime: "Up-time:",
    Uptimedays: "d",
    Uptimehours: "h",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "Sistema Operacional:",
    HealthState: "Saúde",
    HealthStateOK: "OK",
    HealthStateERR: "Fracasso",
    HealthStateCRI: "falha crítica",
    ConnectionType: "Tipo de ligação:",

    start: "Iniciar",
    turnOff: "Desligar",
    shutDown: "Desligar",
    save: "Salvar",
    pause: "Pausa",
    resume: "Iniciar",

    offline: "Offline",
    pingTimeout: "Ping - Tempo Esgotado",

    newServer: "Novo",
    removeServer: "Deletar",
    saveServer: "Salvar",

    serverLabel: "Servidor",
    requiredLabel: "Obrigatório",

    usernameLabel: "Nome do Usuário",
    passwordLabel: "Senha",
    connectionLabel: "Remote desktop",
    consoleOption: "Console",
    terminalOption: "Terminal",
    bothOption: "Ambos",
    noneOption: "Nenhum",
    macAddressLabel: "Endereço MAC",
    ipAddressLabel: "Endereço IP",
    udpPortLabel: "Porta UDP",
    wakeOnLanLabel: "Wake on Lan",

    refreshTime: "Tempo de Atualização",
    seconds: "Segundos",
    showVMLabel: "Mostrar",
    VMLabel: "máquinas virtual",
    VMDetailsLabel: "Detalhes",
    VMCPULabel: "Gráfico de CPU",
    clickBehaviour: "Tipo do Click",
    ondblclickOption: "Duplo Click",
    onclickOption: "Click Único",
    serverControl: "Controle do Servidor",

    madeBy: "Feito por",
    and: "e",
    version: "Versão",
    checkUpdates: "Verificar Atualizações",

    generalTab: "Geral",
    serverTab: "Servidores",

    language: "Idioma",
    translationdBy: "Traduzido por",
    translationdByName: "Mauro Ribeiro"
};

var messages_se_se = {
    unknown: "Ökänt",
    running: "Kör",
    stopped: "Stoppad",
    paused: "Pausad",
    suspended: "Avslagen",
    starting: "Startar",
    snapshot: "Snapshot",
    saving: "Sparar",
    stopping: "Stoppar",
    pausing: "Pausar",
    resuming: "Återupptar",

    NumberOfProcessors: "Processor",
    ProcessorLoad: "Processor Load",
    MemoryUsage: "Memory Usage:",
    HeartBeat: "Heart",
    HeartBeatOK: "OK",
    HeartBeatERR: "Fel",
    HeartBeatNCO: "Ingen kontakt",
    HeartBeatLCO: "Lost Communication",
    Uptime: "Uppetid",
    Uptimedays: "d",
    Uptimehours: "t",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "Operating System",
    HealthState: "Hälsa",
    HealthStateOK: "OK",
    HealthStateERR: "Fel",
    HealthStateCRI: "kritiskt fel",
    ConnectionType: "Anslutningstyp:",

    start: "Start",
    turnOff: "Slå av",
    shutDown: "Avsluta",
    save: "Spara",
    pause: "Pausa",
    resume: "Återuppta",

    offline: "Avslagen",
    pingTimeout: "Ping timeout",

    newServer: "Ny",
    removeServer: "Ta bort",
    saveServer: "Spara",

    serverLabel: "Server",
    requiredLabel: "Obligatorisk",

    usernameLabel: "Brukarnamn",
    passwordLabel: "Lösenord",
    connectionLabel: "Remote desktop",
    consoleOption: "Console",
    terminalOption: "Terminal",
    bothOption: "Båda",
    noneOption: "Ingen",
    macAddressLabel: "MAC-Adress",
    ipAddressLabel: "IP-Adress",
    udpPortLabel: "UDP-Port",
    wakeOnLanLabel: "Wake on Lan",

    refreshTime: "Uppdateringstid",
    seconds: "sekunder",
    showVMLabel: "Visa",
    VMLabel: "virtuella maskiner",
    VMDetailsLabel: "Detaljer",
    VMCPULabel: "CPU-diagrammet",
    clickBehaviour: "Klickbeteende",
    ondblclickOption: "Dubbelklicka",
    onclickOption: "Enkelklicka",
    serverControl: "Serverkontroll",

    madeBy: "Gjord av",
    and: "och",
    version: "Version",
    checkUpdates: "Se efter uppdateringar",

    generalTab: "Generellt",
    serverTab: "Serverar",

    language: "Språk",
    translationdBy: "Översatt av",
    translationdByName: "Camilla Bergström"
};

var messages_fr_fr = {
    unknown: "Inconnu",
    running: "Démarrée",
    stopped: "Arrêtée",
    paused: "En pause",
    suspended: "Suspendue",
    starting: "Démarrage",
    snapshot: "Snapshot",
    saving: "Sauvegarde",
    stopping: "Arrêt",
    pausing: "Pause...",
    resuming: "Restauration",

    NumberOfProcessors: "Le transformateur:",
    ProcessorLoad: "La charge du processeur:",
    MemoryUsage: "Utilisation de la mémoire:",
    HeartBeat: "Heart Beat:",
    HeartBeatOK: "OK",
    HeartBeatERR: "Error",
    HeartBeatNCO: "Pas de contact",
    HeartBeatLCO: "Lost communication",
    Uptime: "Durée de fonctionnent:",
    Uptimedays: "d",
    Uptimehours: "h",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "Système d'exploitation:",
    HealthState: "Santé:",
    HealthStateOK: "OK",
    HealthStateERR: "L'échec",
    HealthStateCRI: "Erreur critique",
    ConnectionType: "Type de connexion:",

    start: "Démarrer",
    turnOff: "Eteindre",
    shutDown: "Arrêter",
    save: "Enregistrer",

    offline: "Indisponible",
    pingTimeout: "Ping timeout",

    newServer: "Nouveau",
    removeServer: "Supprimer",
    saveServer: "Ajouter",

    serverLabel: "Serveur",
    requiredLabel: "Requis",

    usernameLabel: "Nom",
    passwordLabel: "Mot de passe",
    connectionLabel: "Remote Desktop",
    consoleOption: "Console",
    terminalOption: "Terminal",
    bothOption: "Les deux",
    noneOption: "Ni",
    macAddressLabel: "Addresse MAC",
    ipAddressLabel: "Addresse IP",
    udpPortLabel: "Port UDP",
    wakeOnLanLabel: "Wake on Lan",

    refreshTime: "Rafraichissement",
    seconds: "secondes",
    showVMLabel: "Voir",
    VMLabel: "machines virtuelles",
    VMDetailsLabel: "Détails",
    VMCPULabel: "Graphe CPU",
    clickBehaviour: "Comportement au clic",
    ondblclickOption: "Double Click",
    onclickOption: "Simple Click",
    serverControl: "Contrôle des machines",

    madeBy: "Made by",
    and: "et",
    version: "Version",
    checkUpdates: "Vérifier les mises à jour",

    generalTab: "General",
    serverTab: "Serveurs",

    language: "Langue",
    translationdBy: "Traduit par",
    translationdByName: "Thibaut Blanchin"
};

var messages_cn_cn = {
    unknown: "不明",
    running: "執行中",
    stopped: "已停止",
    paused: "已暫停",
    suspended: "已暫停",
    starting: "啟動中",
    snapshot: "快照",
    saving: "儲存中",
    stopping: "停止中",
    pausing: "暫停中",
    resuming: "重新啟動中",

    NumberOfProcessors: "处理器:",
    ProcessorLoad: "处理器负荷:",
    MemoryUsage: "内存使用:",
    HeartBeat: "心跳:",
    HeartBeatOK: "确定",
    HeartBeatERR: "错误",
    HeartBeatNCO: "不接触",
    HeartBeatLCO: "失落的沟通",
    Uptime: "截至时间:",
    Uptimedays: "d",
    Uptimehours: "h",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "操作系统:",
    HealthState: "健康:",
    HealthStateOK: "确定",
    HealthStateERR: "失败",
    HealthStateCRI: "关键失败",
    ConnectionType: "连接类型:",
    
    start: "啟動",
    turnOff: "停止",
    shutDown: "關機",
    save: "儲存",

    offline: "離線",
    pingTimeout: "Ping 逾時",
    
    newServer: "新增",
    removeServer: "刪除",
    saveServer: "儲存",
    
    serverLabel: "伺服器",
    requiredLabel: "必要的",
    
    usernameLabel: "使用者名稱",
    passwordLabel: "密碼",
    connectionLabel: "遠端桌面",
    consoleOption: "終端機",
    terminalOption: "終端機",
    bothOption: "兩者皆是",
    noneOption: "不管是",
    macAddressLabel: "MAC 位址",
    ipAddressLabel: "IP 位址",
    udpPortLabel: "UDP 連接埠",
    wakeOnLanLabel: "Wake on Lan",
    
    refreshTime: "重新整理時間",
    seconds: "秒",
    showVMLabel: "顯示",
    VMLabel: "虚拟机",
    VMDetailsLabel: "詳情",
    VMCPULabel: "CPU 的圖形",
    clickBehaviour: "點擊行為",
    ondblclickOption: "雙擊",
    onclickOption: "單擊",
    serverControl: "控制伺服器",
    
    madeBy: "製作者",
    and: "和",
    version: "版本",
    checkUpdates: "檢查更新",
    
    generalTab: "一般",
    serverTab: "伺服器",

    language: "語言",
    translationdBy: "翻譯者",
    translationdByName: "Jim Liu"
};

var messages_pl_pl = {
    unknown: "Nieznany",
    running: "Dzialajacy",
    stopped: "Zastopowany",
    paused: "Zapauzowany",
    suspended: "Uspiony",
    starting: "Startuje",
    snapshot: "Migawka",
    saving: "Zapisuje",
    stopping: "Stopuje",
    pausing: "Pauzuje",
    resuming: "Wznawiam",
    
    NumberOfProcessors: "procesory",
    ProcessorLoad: "obciążenie procesora:",
    MemoryUsage: "Użycie pamięci",
    Heartbeat: "Heart Beat",
    HeartBeatOK: "OK",
    HeartBeatERR: "Error",
    HeartBeatNCO: "Brak kontaktu",
    HeartBeatLCO: "Lost komunikacji",
    Uptime: "Do czasu",
    Uptimedays: "d",
    Uptimehours: "h",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "System operacyjny",
    HealthState: "Zdrowie",
    HealthStateOK: "OK",
    HealthStateERR: "Brak",
    HealthStateCRI: "niesprawności krytycznego",
    ConnectionType: "Typ połączenia:",
    
    start: "Start",
    turnOff: "Wylaczanie",
    shutDown: "Zamykanie",
    save: "Zapisz",
 
    offline: "Offline",
    pingTimeout: "Ping nie odpowiada",
    
    newServer: "Nowy",
    removeServer: "Usun",
    saveServer: "Zapisz",
    
    serverLabel: "Serwer",
    requiredLabel: "Wymagane",
    
    usernameLabel: "Urzytkownik",
    passwordLabel: "Haslo",
    connectionLabel: "Zdalny pulpit",
    consoleOption: "Konsola",
    terminalOption: "Terminal",
    bothOption: "Oba",
    noneOption: "Ani",
    macAddressLabel: "MAC Adres",
    ipAddressLabel: "Adres IP",
    udpPortLabel: "Port UDP",
    wakeOnLanLabel: "Wake on Lan",
    
    refreshTime: "Odswiez",
    seconds: "sekund",
    showVMLabel: "Pokaż",
    VMLabel: "wirtualne maszyny",
    VMDetailsLabel: "Szczegóły",
    VMCPULabel: "Wykres CPU",
    clickBehaviour: "Podlacz do maszyny",
    ondblclickOption: "Podwojne klikniecie",
    onclickOption: "Pojedyncze klikniecie",
    serverControl: "Kontrola Serwera",
    
    madeBy: "Stworzony przez",
    and: "i",
    version: "Versja",
    checkUpdates: "Sprwadz uaktualnienie",
    
    generalTab: "Glowna",
    serverTab: "Serwery",
 
    language: "Jezyk",
    translationdBy: "Tlumaczone przez",
    translationdByName: "Bartlomiej Malecki"
};

var messages_it_it = {
    unknown: "Sconosciuto",
    running: "Avviato",
    stopped: "Fermato",
    paused: "In pausa",
    suspended: "Sospeso",
    starting: "Avvio",
    snapshot: "Istantanea",
    saving: "Salvataggio in corso",
    stopping: "Arresto in corso",
    pausing: "In pausa",
    resuming: "Ripristino",
 
    NumberOfProcessors: "Processori:",
    ProcessorLoad: "Carico del processore:",
    MemoryUsage: "Utilizzo della memoria:",
    HeartBeat: "Heart beat:",
    HeartBeatOK: "OK",
    HeartBeatERR: "Errore",
    HeartBeatNCO: "Nessuna connessione",
    HeartBeatLCO: "Assenza di comunicazione",
    Uptime: "Up-time:",
    Uptimedays: "g",
    Uptimehours: "o",
    Uptimeminutes: "m",
    Uptimeseconds: "s",
    GuestOperatingSystem: "Sistema operativo:",
    HealthState: "Stato:",
    HealthStateOK: "OK",
    HealthStateERR: "Errore",
    HealthStateCRI: "Errore critico",
    ConnectionType: "Tipo di connessione:",
    
    start: "Avvia",
    turnOff: "Arresta",
    shutDown: "Spegni",
    save: "Salva",
    pause: "Pausa",
    resume: "Ripristina",
 
    offline: "Fuori linea",
    pingTimeout: "Ping timeout",
    
    newServer: "Nuovo",
    removeServer: "Cancella",
    saveServer: "Salva",
    
    serverLabel: "Server",
    requiredLabel: "Richiesto",
    
    usernameLabel: "Utente",
    passwordLabel: "Password",
    connectionLabel: "Desktop Remoto",
    consoleOption: "Console",
    terminalOption: "Terminale",
    bothOption: "Entrambe",
    noneOption: "Nessuna",
    macAddressLabel: "MAC Address",
    ipAddressLabel: "Indirizzo IP",
    udpPortLabel: "Porta UDP",
    wakeOnLanLabel: "Wake on Lan",
    
    refreshTime: "Tempo di Refresh",
    seconds: "secondi",
    showVMLabel: "Mostra",
    VMLabel: "macchine virtuali",
    VMDetailsLabel: "Dettagli",
    VMCPULabel: "CPU grafico",
    clickBehaviour: "Comportamento del Click",
    ondblclickOption: "Doppio Click",
    onclickOption: "Singolo Click",
    serverControl: "Controllo Server",
    
    madeBy: "Creato da",
    and: "e",
    version: "Versione",
    checkUpdates: "Controlla aggiornamenti",
    
    generalTab: "Generale",
    serverTab: "Server",
 
    language: "Lingua",
    translationdBy: "Traduzione di",
    translationdByName: "Adriano Arrigo"
};
